alpha: 0.9
batch_size: 1
beam_size: 4
beta: 5.0
coverage_penalty: summary
length_penalty: wu
model:
- models/en_bert_transformer.pt
output: output.out
src: src.txt
stepwise_penalty: 'true'
verbose: 'true'
#min_length: 55
#max_length: 512
